//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace المشروع.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("المشروع.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _07299005_0e67_45c6_82e6_603299d37315 {
            get {
                object obj = ResourceManager.GetObject("07299005-0e67-45c6-82e6-603299d37315", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1 {
            get {
                object obj = ResourceManager.GetObject("1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _11 {
            get {
                object obj = ResourceManager.GetObject("11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _12 {
            get {
                object obj = ResourceManager.GetObject("12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _122e04a8_a801_4908_8ef5_2b388bbc29c3 {
            get {
                object obj = ResourceManager.GetObject("122e04a8-a801-4908-8ef5-2b388bbc29c3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _13 {
            get {
                object obj = ResourceManager.GetObject("13", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _14 {
            get {
                object obj = ResourceManager.GetObject("14", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1a52bed8_4951_4d66_8968_cacce9178153 {
            get {
                object obj = ResourceManager.GetObject("1a52bed8-4951-4d66-8968-cacce9178153", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1a52bed8_4951_4d66_8968_cacce91781531 {
            get {
                object obj = ResourceManager.GetObject("1a52bed8-4951-4d66-8968-cacce91781531", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1fe62b32_a395_48dc_8b09_751c8877a7cf {
            get {
                object obj = ResourceManager.GetObject("1fe62b32-a395-48dc-8b09-751c8877a7cf", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2 {
            get {
                object obj = ResourceManager.GetObject("2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _21 {
            get {
                object obj = ResourceManager.GetObject("21", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _21a2aa6b_71d2_400f_a5ec_45af19f207a0 {
            get {
                object obj = ResourceManager.GetObject("21a2aa6b-71d2-400f-a5ec-45af19f207a0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2793d20e_64c7_415d_953a_ec9c3b706e7f {
            get {
                object obj = ResourceManager.GetObject("2793d20e-64c7-415d-953a-ec9c3b706e7f", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2montagaat_tbea2 {
            get {
                object obj = ResourceManager.GetObject("2montagaat-tbea2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2montagaat_tbea21 {
            get {
                object obj = ResourceManager.GetObject("2montagaat-tbea21", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3 {
            get {
                object obj = ResourceManager.GetObject("3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _31 {
            get {
                object obj = ResourceManager.GetObject("31", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _37a979e5_8263_4ca2_bd7c_db4daf0ce400 {
            get {
                object obj = ResourceManager.GetObject("37a979e5-8263-4ca2-bd7c-db4daf0ce400", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _39803331_3d95_415c_9ff6_3a1a7369ee7c {
            get {
                object obj = ResourceManager.GetObject("39803331-3d95-415c-9ff6-3a1a7369ee7c", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _39803331_3d95_415c_9ff6_3a1a7369ee7c1 {
            get {
                object obj = ResourceManager.GetObject("39803331-3d95-415c-9ff6-3a1a7369ee7c1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _39803331_3d95_415c_9ff6_3a1a7369ee7c2 {
            get {
                object obj = ResourceManager.GetObject("39803331-3d95-415c-9ff6-3a1a7369ee7c2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _39803331_3d95_415c_9ff6_3a1a7369ee7c3 {
            get {
                object obj = ResourceManager.GetObject("39803331-3d95-415c-9ff6-3a1a7369ee7c3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _39803331_3d95_415c_9ff6_3a1a7369ee7c4 {
            get {
                object obj = ResourceManager.GetObject("39803331-3d95-415c-9ff6-3a1a7369ee7c4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _4 {
            get {
                object obj = ResourceManager.GetObject("4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _41 {
            get {
                object obj = ResourceManager.GetObject("41", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _464a2a9b_6601_407d_8855_52bd4eda0ead {
            get {
                object obj = ResourceManager.GetObject("464a2a9b-6601-407d-8855-52bd4eda0ead", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _515baef4_251f_41a0_8576_6c0a4b5de201 {
            get {
                object obj = ResourceManager.GetObject("515baef4-251f-41a0-8576-6c0a4b5de201", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _581aa691_9cf3_4bf1_9557_47ed5b78cc6a {
            get {
                object obj = ResourceManager.GetObject("581aa691-9cf3-4bf1-9557-47ed5b78cc6a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _5e139747_8cc8_44a8_84ff_676cbc9e220d {
            get {
                object obj = ResourceManager.GetObject("5e139747-8cc8-44a8-84ff-676cbc9e220d", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _5e139747_8cc8_44a8_84ff_676cbc9e220d1 {
            get {
                object obj = ResourceManager.GetObject("5e139747-8cc8-44a8-84ff-676cbc9e220d1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _6e8c0c93_0725_4269_a9ec_fdcabcc874c4 {
            get {
                object obj = ResourceManager.GetObject("6e8c0c93-0725-4269-a9ec-fdcabcc874c4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _7de1449c_e8d9_454e_b9b4_8a4b11e9ddfa {
            get {
                object obj = ResourceManager.GetObject("7de1449c-e8d9-454e-b9b4-8a4b11e9ddfa", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _7f04b26b_b7f4_4e40_ac96_4be003a24e5 {
            get {
                object obj = ResourceManager.GetObject("7f04b26b-b7f4-4e40-ac96-4be003a24e5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _7f04b26b_b7f4_4e40_ac96_4be003a24e51 {
            get {
                object obj = ResourceManager.GetObject("7f04b26b-b7f4-4e40-ac96-4be003a24e51", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _805e5a9d_8522_4318_8937_89ca18c0b330 {
            get {
                object obj = ResourceManager.GetObject("805e5a9d-8522-4318-8937-89ca18c0b330", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _83223be1_38d5_4e0d_b4f5_16e6aa430b07 {
            get {
                object obj = ResourceManager.GetObject("83223be1-38d5-4e0d-b4f5-16e6aa430b07", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _84c870e0_abdf_4fca_a869_2cf13f387629 {
            get {
                object obj = ResourceManager.GetObject("84c870e0-abdf-4fca-a869-2cf13f387629", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _84c870e0_abdf_4fca_a869_2cf13f3876291 {
            get {
                object obj = ResourceManager.GetObject("84c870e0-abdf-4fca-a869-2cf13f3876291", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _84c870e0_abdf_4fca_a869_2cf13f3876292 {
            get {
                object obj = ResourceManager.GetObject("84c870e0-abdf-4fca-a869-2cf13f3876292", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _85c274b3_ad35_4a98_9ad2_bfd3e6f44531 {
            get {
                object obj = ResourceManager.GetObject("85c274b3-ad35-4a98-9ad2-bfd3e6f44531", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _85c274b3_ad35_4a98_9ad2_bfd3e6f445311 {
            get {
                object obj = ResourceManager.GetObject("85c274b3-ad35-4a98-9ad2-bfd3e6f445311", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _8c3da071_5d55_4334_9678_69124dc2d75a {
            get {
                object obj = ResourceManager.GetObject("8c3da071-5d55-4334-9678-69124dc2d75a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _9287ec86_d233_4e81_99e4_a727e0cde8c0 {
            get {
                object obj = ResourceManager.GetObject("9287ec86-d233-4e81-99e4-a727e0cde8c0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _99475053_e69d_4ecb_b0f7_c5a9ea14004a {
            get {
                object obj = ResourceManager.GetObject("99475053-e69d-4ecb-b0f7-c5a9ea14004a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap a1695d6f_341b_4dc5_bb5f_5f817b33db83 {
            get {
                object obj = ResourceManager.GetObject("a1695d6f-341b-4dc5-bb5f-5f817b33db83", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap a2ed413d_a516_4529_b5b5_f811706d85e5 {
            get {
                object obj = ResourceManager.GetObject("a2ed413d-a516-4529-b5b5-f811706d85e5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap a3c675db_373f_49e7_8d68_04261939c8f4 {
            get {
                object obj = ResourceManager.GetObject("a3c675db-373f-49e7-8d68-04261939c8f4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap a3c675db_373f_49e7_8d68_04261939c8f41 {
            get {
                object obj = ResourceManager.GetObject("a3c675db-373f-49e7-8d68-04261939c8f41", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap a66511e3_09f8_471b_b998_9097f20e4637 {
            get {
                object obj = ResourceManager.GetObject("a66511e3-09f8-471b-b998-9097f20e4637", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap a66511e3_09f8_471b_b998_9097f20e46371 {
            get {
                object obj = ResourceManager.GetObject("a66511e3-09f8-471b-b998-9097f20e46371", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aa78ed58_dec2_4fc8_9d08_b261e486a6f7 {
            get {
                object obj = ResourceManager.GetObject("aa78ed58-dec2-4fc8-9d08-b261e486a6f7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap afaeff24_db98_499e_8353_b7e255a10810 {
            get {
                object obj = ResourceManager.GetObject("afaeff24-db98-499e-8353-b7e255a10810", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap b5e2aaa1_5727_46d2_890c_039f55061ec1 {
            get {
                object obj = ResourceManager.GetObject("b5e2aaa1-5727-46d2-890c-039f55061ec1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap c71595fd_1a7e_427f_9277_a1f8bfd9b634 {
            get {
                object obj = ResourceManager.GetObject("c71595fd-1a7e-427f-9277-a1f8bfd9b634", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cdaabedc_bfa7_456c_a669_a7169599fce6 {
            get {
                object obj = ResourceManager.GetObject("cdaabedc-bfa7-456c-a669-a7169599fce6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap d6288655_442b_4636_92e5_250c8e977c76 {
            get {
                object obj = ResourceManager.GetObject("d6288655-442b-4636-92e5-250c8e977c76", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap d78f28c7_09e3_4de7_a7ee_ebae08e23e07 {
            get {
                object obj = ResourceManager.GetObject("d78f28c7-09e3-4de7-a7ee-ebae08e23e07", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap d9a15eed_0059_48a7_9c1c_d5ebc9e9792e {
            get {
                object obj = ResourceManager.GetObject("d9a15eed-0059-48a7-9c1c-d5ebc9e9792e", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap e26973ad_ece7_4867_9852_8745b45989a1 {
            get {
                object obj = ResourceManager.GetObject("e26973ad-ece7-4867-9852-8745b45989a1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap f0792320_f7e4_45c5_a6a9_4ec897ee36c3 {
            get {
                object obj = ResourceManager.GetObject("f0792320-f7e4-45c5-a6a9-4ec897ee36c3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap f2211daf_739d_495f_9189_b9d7ac1e14d5 {
            get {
                object obj = ResourceManager.GetObject("f2211daf-739d-495f-9189-b9d7ac1e14d5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap f3043ce5_969f_4fb4_9640_f3810086164e {
            get {
                object obj = ResourceManager.GetObject("f3043ce5-969f-4fb4-9640-f3810086164e", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WhatsApp_Image_2021_10_25_at_8_00_29_AM {
            get {
                object obj = ResourceManager.GetObject("WhatsApp Image 2021-10-25 at 8.00.29 AM", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WW {
            get {
                object obj = ResourceManager.GetObject("WW", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap باك_قراوند {
            get {
                object obj = ResourceManager.GetObject("باك قراوند", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap باك_قراوند1 {
            get {
                object obj = ResourceManager.GetObject("باك قراوند1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap لوقو {
            get {
                object obj = ResourceManager.GetObject("لوقو", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
